<a href="https://colab.research.google.com/github/Romane-lrnt/GitConcepts/blob/main/Numpy_problems_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [1]:
import numpy as np
vector = np.arange(21)
vector[9:16] *= -1
print(vector)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [2]:
vector = np.arange(15, 56)
print(vector[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


Write a NumPy program to create a 3X4 array and iterate over it.

In [3]:
array = np.random.randint(-10,10,size=(3,4))
for row in array:
    for element in row:
        print(element, end=' ')
    print()

-7 8 8 5 
8 -10 6 -7 
8 4 0 -6 


Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [4]:
vector = np.linspace(5, 50, 10)
print(vector)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [5]:
vector = np.random.randint(0, 11, size=5)
print(vector)

[9 9 0 0 2]


Write a NumPy program to multiply the values of two given vectors.

In [6]:
vector1 = np.array([1, 2, 3, 4])
vector2 = np.array([5, 6, 7, 8])
result = vector1 * vector2
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Result of multiplication:", result)

Vector 1: [1 2 3 4]
Vector 2: [5 6 7 8]
Result of multiplication: [ 5 12 21 32]


Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [7]:
matrice = np.arange(10, 22).reshape(3, 4)
print(matrice)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


Write a NumPy program to find the number of rows and columns in a given matrix.

In [8]:
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
num_rows, num_columns = matrix.shape
print("Number of rows:", num_rows)
print("Number of columns:", num_columns)

Number of rows: 3
Number of columns: 3


Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [9]:
matrix = np.zeros((4, 4), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


Write a NumPy program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [10]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])
print("Array1:", array1)
print("Array2:", array2)
common_values = np.intersect1d(array1, array2)
print("Common values between two arrays:")
print(common_values)

Array1: [ 0 10 20 40 60]
Array2: [10 30 40]
Common values between two arrays:
[10 40]


Write a NumPy program to get the unique elements of an array.
Expected Output:
Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
[2 3]]
Unique elements of the above array:
[1 2 3]

In [11]:
array1d = np.array([10, 10, 20, 20, 30, 30])
print("Original array:")
print(array1d)
unique_elements_1d = np.unique(array1d)
print("Unique elements of the above array:")
print(unique_elements_1d)
array2d = np.array([[1, 1], [2, 3]])
print("Original array:")
print(array2d)
unique_elements_2d = np.unique(array2d)
print("Unique elements of the above array:")
print(unique_elements_2d)

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


Write a NumPy program to compute the cross product of two given vectors.

In [12]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
cross_product = np.cross(vector1, vector2)
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Cross Product:", cross_product)

Vector 1: [1 2 3]
Vector 2: [4 5 6]
Cross Product: [-3  6 -3]


Write a NumPy program to convert cartesian coordinates to polar coordinates of a random 10x2 matrix representing cartesian coordinates.
Expected Output:
[ 0.89225122 0.68774813 0.20392039 1.22093243 1.24435921 1.00358852
0.37378547 0.8534585 0.31999648 0.567451 ]
[ 1.02751197 1.26964967 0.02567519 0.85386412 0.73152767 0.45822494
1.50634505 1.47389983 0.80818521 0.33001182]

In [13]:
cartesian_matrix = np.random.rand(10, 2)
x = cartesian_matrix[:, 0]
y = cartesian_matrix[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
theta_degrees = np.degrees(theta)
print("Cartesian Coordinates:")
print(cartesian_matrix)
print("\nRadius (r):")
print(r)
print("\nAngle (theta) in radians:")
print(theta)
print("\nAngle (theta) in degrees:")
print(theta_degrees)

Cartesian Coordinates:
[[0.16323641 0.30331403]
 [0.59993949 0.68684165]
 [0.17441998 0.47672641]
 [0.17348411 0.78362475]
 [0.38299041 0.24722569]
 [0.99208973 0.02612534]
 [0.95930516 0.79815558]
 [0.48832211 0.71539868]
 [0.84917926 0.8267677 ]
 [0.76641167 0.06057211]]

Radius (r):
[0.3444496  0.91196428 0.50763215 0.80259858 0.45585326 0.99243366
 1.24792576 0.8661719  1.18517941 0.76880156]

Angle (theta) in radians:
[1.07707614 0.8528303  1.2200538  1.35292371 0.57321519 0.02632756
 0.6939593  0.97185253 0.77202649 0.07886944]

Angle (theta) in degrees:
[61.71191708 48.86357685 69.90393373 77.51681831 32.84281122  1.50845829
 39.76093927 55.68304856 44.23385938  4.51888614]


Write a NumPy program to find the closest value (to a given scalar) in an array.
Original array:
[ 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
Value to compare:
34.99062268928913
35

In [14]:
original_array = np.arange(100)
value_to_compare = 34.99062268928913
closest_value = original_array[np.argmin(np.abs(original_array - value_to_compare))]
print("Original array:")
print(original_array)
print("Value to compare:")
print(value_to_compare)
print("Closest value:")
print(closest_value)

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Value to compare:
34.99062268928913
Closest value:
35
